# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Ember CLI Mirage
tagline: 'Easy API mocking for your Ember app'
description: 'A client-side mock server to develop, test and prototype your Ember CLI app'
url: https://github.com/samselikoff/ember-cli-mirage
baseurl: ''
destination: jekyll-tmp/
exclude:
  - node_modules
  - bower_components
  - tmp

gems:
  - jekyll-redirect-from

github:
  repo: https://github.com/samselikoff/ember-cli-mirage

default_version: v0.1.x

defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
